### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm-docs#18]
DotVVM 1.1 is already in beta and contains some changes that have to be reflected in docs. See [Release notes](https://github.com/riganti/dotvvm/releases).

Also https://www.dotvvm.com/docs/tutorials/how-to-start-dnx/latest has to be updated.

**Comment by TomProkop** [comment]
https://www.dotvvm.com/docs/tutorials/basics-javascript-and-css/latest

**Comment by quigamdev** [comment]
Outdated
