### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by CristianT** [riganti/dotvvm-docs#8]
When I search in the page https://www.dotvvm.com/docs/latest any string I get two possible options:
- An error, for instance searching 'abc':
  https://www.dotvvm.com/docs/abc/latest

_Server Error, HTTP 500: Unhandled exception occured
System.IO.FileNotFoundException: Could not find file 'C:\www\www.dotvvm.com\Views\Docs\docsearch.dothtml'._
- Nothing, for instance searching for 'control', the page just reloads and shows the index

**Comment by tomasherceg** [comment]
Thank you, we are working on the resulution.
