### ISSUE TITLE
Server Error, HTTP 500: Unhandled exception occurred

### ISSUE THREAD

**Issue by shibingit** [riganti/dotvvm-docs#93]
Hi,
I am trying to convert my old webforms project to Dotvvm. 
I am getting this error when try to browse the newly added page about.dothtml  

![Screenshot_2021-01-12 Server Error in Application](https://user-images.githubusercontent.com/66682564/104272967-43a2d480-54c4-11eb-8820-47daa1958f9d.png)

**Comment by tomasherceg** [comment]
It looks like the project (or some of its references) is referencing this library which doesn't exist. 
DotVVM tries to load all references on the app startup by default.
You can turn this off using `config.ExperimentalFeatures.ExplicitAssemblyLoading.Enable();` in `DotvvmStartup.cs`. 

Please note that this repo should be used to report errors in the DotVVM documentation. 
To ask questions, please visit our [Gitter chat](https://gitter.im/riganti/dotvvm) - we'll be happy to help you there. :-)
